#
# http://fabiorehm.com/blog/2014/09/11/running-gui-apps-with-docker/
#
# build docker file
# docker build -t firefox .
# to run type in cmd
# sudo docker run -ti --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix firefox

# FROM ubuntu:14.04
# 
# RUN apt-get update && apt-get install -y firefox
# 
# # Replace 1000 with your user / group id
# RUN export uid=1000 gid=1000 && \
#     mkdir -p /home/developer && \
#     echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
#     echo "developer:x:${uid}:" >> /etc/group && \
#     echo "developer ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/developer && \
#     chmod 0440 /etc/sudoers.d/developer && \
#     chown ${uid}:${gid} -R /home/developer
# 
# USER developer
# ENV HOME /home/developer
# CMD /usr/bin/firefox


# FROM ubuntu:18.04
# 
# #RUN apt-get update && apt-get install -y firefox
# RUN apt-get update && apt-get install -y konsole
# 
# # Replace 1000 with your user / group id
# RUN export uid=1000 gid=1000 && \
#     mkdir -p /home/developer && \
#     echo "developer:x:${uid}:${gid}:Developer,,,:/home/developer:/bin/bash" >> /etc/passwd && \
#     echo "developer:x:${uid}:" >> /etc/group && \
#     echo "developer ALL=(ALL) NOPASSWD: ALL" && \
#     chown ${uid}:${gid} -R /home/developer
# 
# USER developer
# ENV HOME /home/developer
# CMD /usr/bin/konsole

FROM hesap/aimpy:jovyan_stable_latest_202002231945

RUN apt-get update && apt-get install -y firefox

USER jovyan
ENV HOME /home/jovyan
CMD jupyter notebook --ip=0.0.0.0 --port=8080

